# coding: utf-8

"""
    GeoSearch

    Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

    The version of the OpenAPI document: 1.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geosearch.models.region_list_response import RegionListResponse

class TestRegionListResponse(unittest.TestCase):
    """RegionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegionListResponse:
        """Test RegionListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegionListResponse`
        """
        model = RegionListResponse()
        if include_optional:
            return RegionListResponse(
                data = [
                    geosearch.models.region.Region(
                        id = 5332921, 
                        geoname_id = 5332921, 
                        country_code = 'US', 
                        admin_code = 'CA', 
                        name = 'California', 
                        ascii_name = 'California', 
                        level = 1, 
                        parent_geoname_id = 6252001, 
                        population = 39538223, 
                        latitude = 36.778, 
                        longitude = -119.418, 
                        country = geosearch.models.country_ref.CountryRef(
                            iso_code = 'US', 
                            name = 'United States', ), 
                        geometry = {type=MultiPolygon, coordinates=[[[[-124.7, 48.4], [-124.6, 48.4], [-124.6, 48.3], [-124.7, 48.4]]]]}, )
                    ],
                meta = geosearch.models.pagination_meta.PaginationMeta(
                    next_cursor = 'eyJpZCI6MjV9', 
                    prev_cursor = 'eyJpZCI6MX0', 
                    has_next = True, 
                    has_prev = False, 
                    count = 25, )
            )
        else:
            return RegionListResponse(
        )
        """

    def testRegionListResponse(self):
        """Test RegionListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
