"""
    GeoAPI

    Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "geoapi-python"
VERSION = "1.2.1"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="GeoAPI",
    author="GeoAPI Support",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "GeoAPI"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT",
    long_description_content_type='text/markdown',
    long_description="""\
    Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the &#x60;X-API-Key&#x60; header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — &#x60;rate_limit_exceeded&#x60; means back off for a moment, &#x60;quota_exceeded&#x60; means the plan&#39;s monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - &#x60;X-RateLimit-Limit&#x60; — requests per second allowed - &#x60;X-RateLimit-Remaining&#x60; — requests remaining in current window - &#x60;X-RateLimit-Reset&#x60; — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   &#x60;quota_exceeded&#x60; response it carries the end of the monthly quota period   rather than the next second boundary. - &#x60;X-Monthly-RateLimit-Limit&#x60; — monthly quota - &#x60;X-Monthly-RateLimit-Remaining&#x60; — monthly requests remaining - &#x60;X-RateLimit-Upgrade&#x60; — advisory message, present only once monthly usage   passes 80% of the plan&#39;s quota - &#x60;Retry-After&#x60; — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   &#x60;X-RateLimit-Reset&#x60;.  ## Pagination List endpoints use cursor-based pagination with &#x60;cursor&#x60; and &#x60;limit&#x60; parameters. Maximum limit is 100. Responses include pagination metadata in the &#x60;meta&#x60; object.  ## Field Selection Use &#x60;?fields&#x3D;name,population&#x60; on any endpoint to receive only the specified fields. 
    """,  # noqa: E501
    package_data={"geoapi": ["py.typed"]},
)
