# coding: utf-8

# flake8: noqa

"""
    GeoAPI

    Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.2.1"

# Define package exports
__all__ = [
    "BatchApi",
    "BoundariesApi",
    "CitiesApi",
    "CountriesApi",
    "HealthApi",
    "IPGeolocationApi",
    "PostalCodesApi",
    "RegionsApi",
    "SearchApi",
    "TimezonesApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AutocompleteListResponse",
    "AutocompleteResult",
    "BatchRequest",
    "Boundary",
    "BoundarySingleResponse",
    "City",
    "CityListResponse",
    "CitySingleResponse",
    "Country",
    "CountryListResponse",
    "CountryRef",
    "CountrySingleResponse",
    "ErrorResponse",
    "ErrorResponseError",
    "ErrorResponseErrorDetailsInner",
    "GeoJSONGeometry",
    "GeoJSONMultiPolygon",
    "GetStatus200Response",
    "GetStatus200ResponseData",
    "HierarchyListResponse",
    "HierarchyNode",
    "IPResult",
    "IPResultCity",
    "IPResultContinent",
    "IPResultCountry",
    "IPResultLocation",
    "IPResultPostal",
    "IPResultRegion",
    "IPSingleResponse",
    "NearbyCity",
    "NearbyCityListResponse",
    "PaginationMeta",
    "PostalCode",
    "PostalCodeListResponse",
    "QuotaDetail",
    "Region",
    "RegionListResponse",
    "RegionRef",
    "RegionSingleResponse",
    "ReverseGeocodeResult",
    "ReverseGeocodeSingleResponse",
    "SearchListResponse",
    "SearchResult",
    "Timezone",
    "TimezoneListResponse",
    "TimezoneSingleResponse",
    "UpgradeDetail",
]

# import apis into sdk package
from geoapi.api.batch_api import BatchApi as BatchApi
from geoapi.api.boundaries_api import BoundariesApi as BoundariesApi
from geoapi.api.cities_api import CitiesApi as CitiesApi
from geoapi.api.countries_api import CountriesApi as CountriesApi
from geoapi.api.health_api import HealthApi as HealthApi
from geoapi.api.ip_geolocation_api import IPGeolocationApi as IPGeolocationApi
from geoapi.api.postal_codes_api import PostalCodesApi as PostalCodesApi
from geoapi.api.regions_api import RegionsApi as RegionsApi
from geoapi.api.search_api import SearchApi as SearchApi
from geoapi.api.timezones_api import TimezonesApi as TimezonesApi

# import ApiClient
from geoapi.api_response import ApiResponse as ApiResponse
from geoapi.api_client import ApiClient as ApiClient
from geoapi.configuration import Configuration as Configuration
from geoapi.exceptions import OpenApiException as OpenApiException
from geoapi.exceptions import ApiTypeError as ApiTypeError
from geoapi.exceptions import ApiValueError as ApiValueError
from geoapi.exceptions import ApiKeyError as ApiKeyError
from geoapi.exceptions import ApiAttributeError as ApiAttributeError
from geoapi.exceptions import ApiException as ApiException

# import models into sdk package
from geoapi.models.autocomplete_list_response import AutocompleteListResponse as AutocompleteListResponse
from geoapi.models.autocomplete_result import AutocompleteResult as AutocompleteResult
from geoapi.models.batch_request import BatchRequest as BatchRequest
from geoapi.models.boundary import Boundary as Boundary
from geoapi.models.boundary_single_response import BoundarySingleResponse as BoundarySingleResponse
from geoapi.models.city import City as City
from geoapi.models.city_list_response import CityListResponse as CityListResponse
from geoapi.models.city_single_response import CitySingleResponse as CitySingleResponse
from geoapi.models.country import Country as Country
from geoapi.models.country_list_response import CountryListResponse as CountryListResponse
from geoapi.models.country_ref import CountryRef as CountryRef
from geoapi.models.country_single_response import CountrySingleResponse as CountrySingleResponse
from geoapi.models.error_response import ErrorResponse as ErrorResponse
from geoapi.models.error_response_error import ErrorResponseError as ErrorResponseError
from geoapi.models.error_response_error_details_inner import ErrorResponseErrorDetailsInner as ErrorResponseErrorDetailsInner
from geoapi.models.geo_json_geometry import GeoJSONGeometry as GeoJSONGeometry
from geoapi.models.geo_json_multi_polygon import GeoJSONMultiPolygon as GeoJSONMultiPolygon
from geoapi.models.get_status200_response import GetStatus200Response as GetStatus200Response
from geoapi.models.get_status200_response_data import GetStatus200ResponseData as GetStatus200ResponseData
from geoapi.models.hierarchy_list_response import HierarchyListResponse as HierarchyListResponse
from geoapi.models.hierarchy_node import HierarchyNode as HierarchyNode
from geoapi.models.ip_result import IPResult as IPResult
from geoapi.models.ip_result_city import IPResultCity as IPResultCity
from geoapi.models.ip_result_continent import IPResultContinent as IPResultContinent
from geoapi.models.ip_result_country import IPResultCountry as IPResultCountry
from geoapi.models.ip_result_location import IPResultLocation as IPResultLocation
from geoapi.models.ip_result_postal import IPResultPostal as IPResultPostal
from geoapi.models.ip_result_region import IPResultRegion as IPResultRegion
from geoapi.models.ip_single_response import IPSingleResponse as IPSingleResponse
from geoapi.models.nearby_city import NearbyCity as NearbyCity
from geoapi.models.nearby_city_list_response import NearbyCityListResponse as NearbyCityListResponse
from geoapi.models.pagination_meta import PaginationMeta as PaginationMeta
from geoapi.models.postal_code import PostalCode as PostalCode
from geoapi.models.postal_code_list_response import PostalCodeListResponse as PostalCodeListResponse
from geoapi.models.quota_detail import QuotaDetail as QuotaDetail
from geoapi.models.region import Region as Region
from geoapi.models.region_list_response import RegionListResponse as RegionListResponse
from geoapi.models.region_ref import RegionRef as RegionRef
from geoapi.models.region_single_response import RegionSingleResponse as RegionSingleResponse
from geoapi.models.reverse_geocode_result import ReverseGeocodeResult as ReverseGeocodeResult
from geoapi.models.reverse_geocode_single_response import ReverseGeocodeSingleResponse as ReverseGeocodeSingleResponse
from geoapi.models.search_list_response import SearchListResponse as SearchListResponse
from geoapi.models.search_result import SearchResult as SearchResult
from geoapi.models.timezone import Timezone as Timezone
from geoapi.models.timezone_list_response import TimezoneListResponse as TimezoneListResponse
from geoapi.models.timezone_single_response import TimezoneSingleResponse as TimezoneSingleResponse
from geoapi.models.upgrade_detail import UpgradeDetail as UpgradeDetail

