# coding: utf-8

# flake8: noqa
"""
    GeoAPI

    Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from geoapi.models.autocomplete_list_response import AutocompleteListResponse
from geoapi.models.autocomplete_result import AutocompleteResult
from geoapi.models.batch_request import BatchRequest
from geoapi.models.boundary import Boundary
from geoapi.models.boundary_single_response import BoundarySingleResponse
from geoapi.models.city import City
from geoapi.models.city_list_response import CityListResponse
from geoapi.models.city_single_response import CitySingleResponse
from geoapi.models.country import Country
from geoapi.models.country_list_response import CountryListResponse
from geoapi.models.country_ref import CountryRef
from geoapi.models.country_single_response import CountrySingleResponse
from geoapi.models.error_response import ErrorResponse
from geoapi.models.error_response_error import ErrorResponseError
from geoapi.models.error_response_error_details_inner import ErrorResponseErrorDetailsInner
from geoapi.models.geo_json_geometry import GeoJSONGeometry
from geoapi.models.geo_json_multi_polygon import GeoJSONMultiPolygon
from geoapi.models.get_status200_response import GetStatus200Response
from geoapi.models.get_status200_response_data import GetStatus200ResponseData
from geoapi.models.hierarchy_list_response import HierarchyListResponse
from geoapi.models.hierarchy_node import HierarchyNode
from geoapi.models.ip_result import IPResult
from geoapi.models.ip_result_city import IPResultCity
from geoapi.models.ip_result_continent import IPResultContinent
from geoapi.models.ip_result_country import IPResultCountry
from geoapi.models.ip_result_location import IPResultLocation
from geoapi.models.ip_result_postal import IPResultPostal
from geoapi.models.ip_result_region import IPResultRegion
from geoapi.models.ip_single_response import IPSingleResponse
from geoapi.models.nearby_city import NearbyCity
from geoapi.models.nearby_city_list_response import NearbyCityListResponse
from geoapi.models.pagination_meta import PaginationMeta
from geoapi.models.postal_code import PostalCode
from geoapi.models.postal_code_list_response import PostalCodeListResponse
from geoapi.models.quota_detail import QuotaDetail
from geoapi.models.region import Region
from geoapi.models.region_list_response import RegionListResponse
from geoapi.models.region_ref import RegionRef
from geoapi.models.region_single_response import RegionSingleResponse
from geoapi.models.reverse_geocode_result import ReverseGeocodeResult
from geoapi.models.reverse_geocode_single_response import ReverseGeocodeSingleResponse
from geoapi.models.search_list_response import SearchListResponse
from geoapi.models.search_result import SearchResult
from geoapi.models.timezone import Timezone
from geoapi.models.timezone_list_response import TimezoneListResponse
from geoapi.models.timezone_single_response import TimezoneSingleResponse
from geoapi.models.upgrade_detail import UpgradeDetail

