# coding: utf-8

"""
    GeoAPI

    Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from geoapi.models.geo_json_multi_polygon import GeoJSONMultiPolygon
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Country(BaseModel):
    """
    Country
    """ # noqa: E501
    id: Optional[StrictInt] = None
    geoname_id: Optional[StrictInt] = None
    iso_code: Optional[StrictStr] = None
    iso3_code: Optional[StrictStr] = None
    iso_numeric: Optional[StrictInt] = None
    fips_code: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    capital: Optional[StrictStr] = None
    area_sq_km: Optional[Union[StrictFloat, StrictInt]] = None
    population: Optional[StrictInt] = None
    continent_code: Optional[StrictStr] = None
    tld: Optional[StrictStr] = None
    currency_code: Optional[StrictStr] = None
    currency_name: Optional[StrictStr] = None
    phone: Optional[StrictStr] = None
    postal_code_format: Optional[StrictStr] = None
    postal_code_regex: Optional[StrictStr] = None
    languages: Optional[List[StrictStr]] = None
    neighbours: Optional[List[StrictStr]] = None
    latitude: Optional[Union[StrictFloat, StrictInt]] = None
    longitude: Optional[Union[StrictFloat, StrictInt]] = None
    flag_emoji: Optional[StrictStr] = None
    geometry: Optional[GeoJSONMultiPolygon] = Field(default=None, description="Country boundary. Returned by default on `GET /v1/countries/{code}` and on request via `?fields=geometry` on `GET /v1/countries`.  NOT TIER-GATED. Country geometry is served on every plan, including Free. Region geometry is gated — see the `Region` schema.")
    __properties: ClassVar[List[str]] = ["id", "geoname_id", "iso_code", "iso3_code", "iso_numeric", "fips_code", "name", "capital", "area_sq_km", "population", "continent_code", "tld", "currency_code", "currency_name", "phone", "postal_code_format", "postal_code_regex", "languages", "neighbours", "latitude", "longitude", "flag_emoji", "geometry"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Country from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of geometry
        if self.geometry:
            _dict['geometry'] = self.geometry.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Country from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "geoname_id": obj.get("geoname_id"),
            "iso_code": obj.get("iso_code"),
            "iso3_code": obj.get("iso3_code"),
            "iso_numeric": obj.get("iso_numeric"),
            "fips_code": obj.get("fips_code"),
            "name": obj.get("name"),
            "capital": obj.get("capital"),
            "area_sq_km": obj.get("area_sq_km"),
            "population": obj.get("population"),
            "continent_code": obj.get("continent_code"),
            "tld": obj.get("tld"),
            "currency_code": obj.get("currency_code"),
            "currency_name": obj.get("currency_name"),
            "phone": obj.get("phone"),
            "postal_code_format": obj.get("postal_code_format"),
            "postal_code_regex": obj.get("postal_code_regex"),
            "languages": obj.get("languages"),
            "neighbours": obj.get("neighbours"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "flag_emoji": obj.get("flag_emoji"),
            "geometry": GeoJSONMultiPolygon.from_dict(obj["geometry"]) if obj.get("geometry") is not None else None
        })
        return _obj


