"""
    GeoAPI

    Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

    The version of the OpenAPI document: 1.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from geoapi.models.timezone_list_response import TimezoneListResponse
from geoapi.models.timezone_single_response import TimezoneSingleResponse

from geoapi.api_client import ApiClient, RequestSerialized
from geoapi.api_response import ApiResponse
from geoapi.rest import RESTResponseType


class TimezonesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_timezone(
        self,
        tz_id: Annotated[StrictStr, Field(description="IANA timezone ID (e.g., America/New_York)")],
        lang: Annotated[Optional[Annotated[str, Field(min_length=2, strict=True, max_length=5)]], Field(description="ISO 639-1 language code for localized names (e.g., de, fr, ja)")] = None,
        fields: Annotated[Optional[StrictStr], Field(description="Comma-separated list of fields to include in the response")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> TimezoneSingleResponse:
        """Get timezone by IANA ID

        Returns a single timezone by its IANA identifier. Note: IANA timezone IDs contain slashes (e.g., America/New_York), so the path uses a wildcard match. 

        :param tz_id: IANA timezone ID (e.g., America/New_York) (required)
        :type tz_id: str
        :param lang: ISO 639-1 language code for localized names (e.g., de, fr, ja)
        :type lang: str
        :param fields: Comma-separated list of fields to include in the response
        :type fields: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_timezone_serialize(
            tz_id=tz_id,
            lang=lang,
            fields=fields,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TimezoneSingleResponse",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '404': "ErrorResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_timezone_with_http_info(
        self,
        tz_id: Annotated[StrictStr, Field(description="IANA timezone ID (e.g., America/New_York)")],
        lang: Annotated[Optional[Annotated[str, Field(min_length=2, strict=True, max_length=5)]], Field(description="ISO 639-1 language code for localized names (e.g., de, fr, ja)")] = None,
        fields: Annotated[Optional[StrictStr], Field(description="Comma-separated list of fields to include in the response")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[TimezoneSingleResponse]:
        """Get timezone by IANA ID

        Returns a single timezone by its IANA identifier. Note: IANA timezone IDs contain slashes (e.g., America/New_York), so the path uses a wildcard match. 

        :param tz_id: IANA timezone ID (e.g., America/New_York) (required)
        :type tz_id: str
        :param lang: ISO 639-1 language code for localized names (e.g., de, fr, ja)
        :type lang: str
        :param fields: Comma-separated list of fields to include in the response
        :type fields: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_timezone_serialize(
            tz_id=tz_id,
            lang=lang,
            fields=fields,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TimezoneSingleResponse",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '404': "ErrorResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_timezone_without_preload_content(
        self,
        tz_id: Annotated[StrictStr, Field(description="IANA timezone ID (e.g., America/New_York)")],
        lang: Annotated[Optional[Annotated[str, Field(min_length=2, strict=True, max_length=5)]], Field(description="ISO 639-1 language code for localized names (e.g., de, fr, ja)")] = None,
        fields: Annotated[Optional[StrictStr], Field(description="Comma-separated list of fields to include in the response")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get timezone by IANA ID

        Returns a single timezone by its IANA identifier. Note: IANA timezone IDs contain slashes (e.g., America/New_York), so the path uses a wildcard match. 

        :param tz_id: IANA timezone ID (e.g., America/New_York) (required)
        :type tz_id: str
        :param lang: ISO 639-1 language code for localized names (e.g., de, fr, ja)
        :type lang: str
        :param fields: Comma-separated list of fields to include in the response
        :type fields: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_timezone_serialize(
            tz_id=tz_id,
            lang=lang,
            fields=fields,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TimezoneSingleResponse",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '404': "ErrorResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_timezone_serialize(
        self,
        tz_id,
        lang,
        fields,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if tz_id is not None:
            _path_params['tzId'] = tz_id
        # process the query parameters
        if lang is not None:
            
            _query_params.append(('lang', lang))
            
        if fields is not None:
            
            _query_params.append(('fields', fields))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'apiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/timezones/{tzId}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_timezones(
        self,
        lang: Annotated[Optional[Annotated[str, Field(min_length=2, strict=True, max_length=5)]], Field(description="ISO 639-1 language code for localized names (e.g., de, fr, ja)")] = None,
        country: Annotated[Optional[StrictStr], Field(description="Filter by ISO alpha-2 country code")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Pagination cursor from a previous response")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Number of results per page (1-100, default 25)")] = None,
        fields: Annotated[Optional[StrictStr], Field(description="Comma-separated list of fields to include in the response")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Sort field. Allowed: timezone_id, gmt_offset, country_code.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> TimezoneListResponse:
        """List timezones

        Returns a paginated list of timezones with optional filtering by country.

        :param lang: ISO 639-1 language code for localized names (e.g., de, fr, ja)
        :type lang: str
        :param country: Filter by ISO alpha-2 country code
        :type country: str
        :param cursor: Pagination cursor from a previous response
        :type cursor: str
        :param limit: Number of results per page (1-100, default 25)
        :type limit: int
        :param fields: Comma-separated list of fields to include in the response
        :type fields: str
        :param sort: Sort field. Allowed: timezone_id, gmt_offset, country_code.
        :type sort: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_timezones_serialize(
            lang=lang,
            country=country,
            cursor=cursor,
            limit=limit,
            fields=fields,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TimezoneListResponse",
            '401': "ErrorResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_timezones_with_http_info(
        self,
        lang: Annotated[Optional[Annotated[str, Field(min_length=2, strict=True, max_length=5)]], Field(description="ISO 639-1 language code for localized names (e.g., de, fr, ja)")] = None,
        country: Annotated[Optional[StrictStr], Field(description="Filter by ISO alpha-2 country code")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Pagination cursor from a previous response")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Number of results per page (1-100, default 25)")] = None,
        fields: Annotated[Optional[StrictStr], Field(description="Comma-separated list of fields to include in the response")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Sort field. Allowed: timezone_id, gmt_offset, country_code.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[TimezoneListResponse]:
        """List timezones

        Returns a paginated list of timezones with optional filtering by country.

        :param lang: ISO 639-1 language code for localized names (e.g., de, fr, ja)
        :type lang: str
        :param country: Filter by ISO alpha-2 country code
        :type country: str
        :param cursor: Pagination cursor from a previous response
        :type cursor: str
        :param limit: Number of results per page (1-100, default 25)
        :type limit: int
        :param fields: Comma-separated list of fields to include in the response
        :type fields: str
        :param sort: Sort field. Allowed: timezone_id, gmt_offset, country_code.
        :type sort: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_timezones_serialize(
            lang=lang,
            country=country,
            cursor=cursor,
            limit=limit,
            fields=fields,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TimezoneListResponse",
            '401': "ErrorResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_timezones_without_preload_content(
        self,
        lang: Annotated[Optional[Annotated[str, Field(min_length=2, strict=True, max_length=5)]], Field(description="ISO 639-1 language code for localized names (e.g., de, fr, ja)")] = None,
        country: Annotated[Optional[StrictStr], Field(description="Filter by ISO alpha-2 country code")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Pagination cursor from a previous response")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Number of results per page (1-100, default 25)")] = None,
        fields: Annotated[Optional[StrictStr], Field(description="Comma-separated list of fields to include in the response")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Sort field. Allowed: timezone_id, gmt_offset, country_code.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List timezones

        Returns a paginated list of timezones with optional filtering by country.

        :param lang: ISO 639-1 language code for localized names (e.g., de, fr, ja)
        :type lang: str
        :param country: Filter by ISO alpha-2 country code
        :type country: str
        :param cursor: Pagination cursor from a previous response
        :type cursor: str
        :param limit: Number of results per page (1-100, default 25)
        :type limit: int
        :param fields: Comma-separated list of fields to include in the response
        :type fields: str
        :param sort: Sort field. Allowed: timezone_id, gmt_offset, country_code.
        :type sort: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_timezones_serialize(
            lang=lang,
            country=country,
            cursor=cursor,
            limit=limit,
            fields=fields,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TimezoneListResponse",
            '401': "ErrorResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_timezones_serialize(
        self,
        lang,
        country,
        cursor,
        limit,
        fields,
        sort,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if lang is not None:
            
            _query_params.append(('lang', lang))
            
        if country is not None:
            
            _query_params.append(('country', country))
            
        if cursor is not None:
            
            _query_params.append(('cursor', cursor))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if fields is not None:
            
            _query_params.append(('fields', fields))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'apiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/timezones',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


