# coding: utf-8

# flake8: noqa

"""
    GeoSearch

    Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.3.0"

# Define package exports
__all__ = [
    "BatchApi",
    "BoundariesApi",
    "CitiesApi",
    "CountriesApi",
    "HealthApi",
    "IPGeolocationApi",
    "PostalCodesApi",
    "RegionsApi",
    "SearchApi",
    "TimezonesApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AutocompleteListResponse",
    "AutocompleteResult",
    "BatchRequest",
    "Boundary",
    "BoundarySingleResponse",
    "City",
    "CityListResponse",
    "CitySingleResponse",
    "Country",
    "CountryListResponse",
    "CountryRef",
    "CountrySingleResponse",
    "ErrorResponse",
    "ErrorResponseError",
    "ErrorResponseErrorDetailsInner",
    "GeoJSONGeometry",
    "GeoJSONMultiPolygon",
    "GetStatus200Response",
    "GetStatus200ResponseData",
    "HierarchyListResponse",
    "HierarchyNode",
    "IPResult",
    "IPResultCity",
    "IPResultContinent",
    "IPResultCountry",
    "IPResultLocation",
    "IPResultPostal",
    "IPResultRegion",
    "IPSingleResponse",
    "NearbyCity",
    "NearbyCityListResponse",
    "PaginationMeta",
    "PostalCode",
    "PostalCodeListResponse",
    "QuotaDetail",
    "Region",
    "RegionListResponse",
    "RegionRef",
    "RegionSingleResponse",
    "ReverseGeocodeResult",
    "ReverseGeocodeSingleResponse",
    "SearchListResponse",
    "SearchResult",
    "Timezone",
    "TimezoneListResponse",
    "TimezoneSingleResponse",
    "UpgradeDetail",
]

# import apis into sdk package
from geosearch.api.batch_api import BatchApi as BatchApi
from geosearch.api.boundaries_api import BoundariesApi as BoundariesApi
from geosearch.api.cities_api import CitiesApi as CitiesApi
from geosearch.api.countries_api import CountriesApi as CountriesApi
from geosearch.api.health_api import HealthApi as HealthApi
from geosearch.api.ip_geolocation_api import IPGeolocationApi as IPGeolocationApi
from geosearch.api.postal_codes_api import PostalCodesApi as PostalCodesApi
from geosearch.api.regions_api import RegionsApi as RegionsApi
from geosearch.api.search_api import SearchApi as SearchApi
from geosearch.api.timezones_api import TimezonesApi as TimezonesApi

# import ApiClient
from geosearch.api_response import ApiResponse as ApiResponse
from geosearch.api_client import ApiClient as ApiClient
from geosearch.configuration import Configuration as Configuration
from geosearch.exceptions import OpenApiException as OpenApiException
from geosearch.exceptions import ApiTypeError as ApiTypeError
from geosearch.exceptions import ApiValueError as ApiValueError
from geosearch.exceptions import ApiKeyError as ApiKeyError
from geosearch.exceptions import ApiAttributeError as ApiAttributeError
from geosearch.exceptions import ApiException as ApiException

# import models into sdk package
from geosearch.models.autocomplete_list_response import AutocompleteListResponse as AutocompleteListResponse
from geosearch.models.autocomplete_result import AutocompleteResult as AutocompleteResult
from geosearch.models.batch_request import BatchRequest as BatchRequest
from geosearch.models.boundary import Boundary as Boundary
from geosearch.models.boundary_single_response import BoundarySingleResponse as BoundarySingleResponse
from geosearch.models.city import City as City
from geosearch.models.city_list_response import CityListResponse as CityListResponse
from geosearch.models.city_single_response import CitySingleResponse as CitySingleResponse
from geosearch.models.country import Country as Country
from geosearch.models.country_list_response import CountryListResponse as CountryListResponse
from geosearch.models.country_ref import CountryRef as CountryRef
from geosearch.models.country_single_response import CountrySingleResponse as CountrySingleResponse
from geosearch.models.error_response import ErrorResponse as ErrorResponse
from geosearch.models.error_response_error import ErrorResponseError as ErrorResponseError
from geosearch.models.error_response_error_details_inner import ErrorResponseErrorDetailsInner as ErrorResponseErrorDetailsInner
from geosearch.models.geo_json_geometry import GeoJSONGeometry as GeoJSONGeometry
from geosearch.models.geo_json_multi_polygon import GeoJSONMultiPolygon as GeoJSONMultiPolygon
from geosearch.models.get_status200_response import GetStatus200Response as GetStatus200Response
from geosearch.models.get_status200_response_data import GetStatus200ResponseData as GetStatus200ResponseData
from geosearch.models.hierarchy_list_response import HierarchyListResponse as HierarchyListResponse
from geosearch.models.hierarchy_node import HierarchyNode as HierarchyNode
from geosearch.models.ip_result import IPResult as IPResult
from geosearch.models.ip_result_city import IPResultCity as IPResultCity
from geosearch.models.ip_result_continent import IPResultContinent as IPResultContinent
from geosearch.models.ip_result_country import IPResultCountry as IPResultCountry
from geosearch.models.ip_result_location import IPResultLocation as IPResultLocation
from geosearch.models.ip_result_postal import IPResultPostal as IPResultPostal
from geosearch.models.ip_result_region import IPResultRegion as IPResultRegion
from geosearch.models.ip_single_response import IPSingleResponse as IPSingleResponse
from geosearch.models.nearby_city import NearbyCity as NearbyCity
from geosearch.models.nearby_city_list_response import NearbyCityListResponse as NearbyCityListResponse
from geosearch.models.pagination_meta import PaginationMeta as PaginationMeta
from geosearch.models.postal_code import PostalCode as PostalCode
from geosearch.models.postal_code_list_response import PostalCodeListResponse as PostalCodeListResponse
from geosearch.models.quota_detail import QuotaDetail as QuotaDetail
from geosearch.models.region import Region as Region
from geosearch.models.region_list_response import RegionListResponse as RegionListResponse
from geosearch.models.region_ref import RegionRef as RegionRef
from geosearch.models.region_single_response import RegionSingleResponse as RegionSingleResponse
from geosearch.models.reverse_geocode_result import ReverseGeocodeResult as ReverseGeocodeResult
from geosearch.models.reverse_geocode_single_response import ReverseGeocodeSingleResponse as ReverseGeocodeSingleResponse
from geosearch.models.search_list_response import SearchListResponse as SearchListResponse
from geosearch.models.search_result import SearchResult as SearchResult
from geosearch.models.timezone import Timezone as Timezone
from geosearch.models.timezone_list_response import TimezoneListResponse as TimezoneListResponse
from geosearch.models.timezone_single_response import TimezoneSingleResponse as TimezoneSingleResponse
from geosearch.models.upgrade_detail import UpgradeDetail as UpgradeDetail

