# coding: utf-8

"""
    GeoSearch

    Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

    The version of the OpenAPI document: 1.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from geosearch.models.country_ref import CountryRef
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PostalCode(BaseModel):
    """
    PostalCode
    """ # noqa: E501
    id: Optional[StrictInt] = None
    country_code: Optional[StrictStr] = None
    postal_code: Optional[StrictStr] = None
    place_name: Optional[StrictStr] = None
    admin_name1: Optional[StrictStr] = None
    admin_code1: Optional[StrictStr] = None
    admin_name2: Optional[StrictStr] = None
    admin_code2: Optional[StrictStr] = None
    admin_name3: Optional[StrictStr] = Field(default=None, description="Third-level administrative area. Empty where the source data defines none — most US rows, including this example.")
    admin_code3: Optional[StrictStr] = Field(default=None, description="Third-level administrative code. Empty where the source data defines none — most US rows, including this example.")
    latitude: Optional[Union[StrictFloat, StrictInt]] = None
    longitude: Optional[Union[StrictFloat, StrictInt]] = None
    accuracy: Optional[StrictInt] = None
    country: Optional[CountryRef] = None
    __properties: ClassVar[List[str]] = ["id", "country_code", "postal_code", "place_name", "admin_name1", "admin_code1", "admin_name2", "admin_code2", "admin_name3", "admin_code3", "latitude", "longitude", "accuracy", "country"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostalCode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of country
        if self.country:
            _dict['country'] = self.country.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostalCode from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "country_code": obj.get("country_code"),
            "postal_code": obj.get("postal_code"),
            "place_name": obj.get("place_name"),
            "admin_name1": obj.get("admin_name1"),
            "admin_code1": obj.get("admin_code1"),
            "admin_name2": obj.get("admin_name2"),
            "admin_code2": obj.get("admin_code2"),
            "admin_name3": obj.get("admin_name3"),
            "admin_code3": obj.get("admin_code3"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "accuracy": obj.get("accuracy"),
            "country": CountryRef.from_dict(obj["country"]) if obj.get("country") is not None else None
        })
        return _obj


